NBA_TEAMS_WIKI_TEAMS_MAPPER = {
	"Boston Celtics": "Boston",
	"Brooklyn Nets": "Brooklyn",
	"New York Knicks": "New York",
	"Philadelphia 76ers": "Philadelphia",
	"Toronto Raptors": "Toronto",
	"Chicago Bulls": "Chicago",
	"Cleveland Cavaliers": "Cleveland",
	"Detroit Pistons": "Detroit",
	"Indiana Pacers": "Indiana",
	"Milwaukee Bucks": "Milwaukee",
	"Atlanta Hawks": "Atlanta",
	"Charlotte Hornets": "Charlotte",
	"Miami Heat": "Miami",
	"Orlando Magic": "Orlando",
	"Washington Wizards": "Washington",
	"Denver Nuggets": "Denver",
	"Minnesota Timberwolves": "Minnesota",
	"Oklahoma City Thunder": "Oklahoma City",
	"Portland Trail Blazers": "Portland",
	"Golden State Warriors": "Golden State",
	"Los Angeles Lakers": "L.A. Lakers",
	"Los Angeles Clippers": "L.A. Clippers",
	"Phoenix Suns": "Phoenix",
	"Sacramento Kings": "Sacramento`",
	"Dallas Mavericks": "Dallas",
	"Houston Rockets": "Houston",
	"Memphis Grizzlies": "Memphis",
	"New Orleans Pelicans": "New Orleans",
	"San Antonio Spurs": "San Antonio"
};