NBA_TEAMS_WIKI_TEAMS_MAPPER = {
	"Boston Celtics": "Boston Celtics",
	"Brooklyn Nets": "Brooklyn Nets",
	"New York Knicks": "New York Knicks",
	"Philadelphia 76ers": "Philadelphia 76ers",
	"Toronto Raptors": "Toronto Raptors",
	"Chicago Bulls": "Chicago Bulls",
	"Cleveland Cavaliers": "Cleveland Cavaliers",
	"Detroit Pistons": "Detroit Pistons",
	"Indiana Pacers": "Indiana Pacers",
	"Milwaukee Bucks": "Milwaukee Bucks",
	"Atlanta Hawks": "Atlanta Hawks",
	"Charlotte Hornets": "Charlotte Hornets",
	"Miami Heat": "Miami Heat",
	"Orlando Magic": "Orlando Magic",
	"Washington Wizards": "Washington Wizards",
	"Denver Nuggets": "Denver Nuggets",
	"Minnesota Timberwolves": "Minnesota Timberwolves",
	"Oklahoma City Thunder": "Oklahoma City Thunder",
	"Portland Trail Blazers": "Portland Trail Blazers",
	"Golden State Warriors": "Golden State Warriors",
	"Los Angeles Lakers": "Los Angeles Lakers",
	"Los Angeles Clippers": "LA Clippers",
	"Phoenix Suns": "Phoenix Suns",
	"Sacramento Kings": "Sacramento Kings",
	"Dallas Mavericks": "Dallas Mavericks",
	"Houston Rockets": "Houston Rockets",
	"Memphis Grizzlies": "Memphis Grizzlies",
	"New Orleans Pelicans": "New Orleans Pelicans",
	"San Antonio Spurs": "San Antonio Spurs"
};

NFL_TEAMS_WIKI_TEAMS_MAPPER = {
	"New England Patriots": "New England Patriots",
	"Miami Dolphins": "Miami Dolphins",
	"Buffalo Bills":"Buffalo Bills",
	"New York Jets":"New York Jets",
	"Baltimore Ravens":"Baltimore Ravens",
	"Pittsburgh Steelers":"Pittsburgh Steelers",
	"Cincinnati Bengals":"Cincinnati Bengals",
	"Cleveland Browns":"Cleveland Browns",
	"Houston Texans":"Houston Texans",
	"Tennessee Titans": "Tennessee Titans",
	"Indianapolis Colts":"Indianapolis Colts",
	"Jacksonville Jaguars":"Jacksonville Jaguars",
	"Kansas City Chiefs":"Kansas City Chiefs",
	"Oakland Raiders":"Oakland Raiders",
	"Denver Broncos":"Denver Broncos",
	"San Diego Chargers":"San Diego Chargers",
	"Dallas Cowboys":"Dallas Cowboys",
	"New York Giants":"New York Giants",
	"Washington Redskins":"Washington Redskins",
	"Philadelphia Eagles":"Philadelphia Eagles",
	"Detroit Lions":"Detroit Lions",
	"Minnesota Vikings":"Minnesota Vikings",
	"Green Bay Packers":"Green Bay Packers",
	"Chicago Bears":"Chicago Bears",
	"Atlanta Falcons":"Atlanta Falcons",
	"Tampa Bay Buccaneers":"Tampa Bay Buccaneers",
	"New Orleans Saints":"New Orleans Saints",
	"Carolina Panthers":"Carolina Panthers",
	"Seattle Seahawks":"Seattle Seahawks",
	"Arizona Cardinals":"Arizona Cardinals",
	"Los Angeles Rams":"Los Angeles Rams",
	"San Francisco 49ers":"San Francisco 49ers"
};