NBA_TEAMS_WIKI_TEAMS_MAPPER = {
	"Boston Celtics": "Boston Celtics",
	"Brooklyn Nets": "Brooklyn Nets",
	"New York Knicks": "New York Knicks",
	"Philadelphia 76ers": "Philadelphia 76ers",
	"Toronto Raptors": "Toronto Raptors",
	"Chicago Bulls": "Chicago Bulls",
	"Cleveland Cavaliers": "Cleveland Cavaliers",
	"Detroit Pistons": "Detroit Pistons",
	"Indiana Pacers": "Indiana Pacers",
	"Milwaukee Bucks": "Milwaukee Bucks",
	"Atlanta Hawks": "Atlanta Hawks",
	"Charlotte Hornets": "Charlotte Hornets",
	"Miami Heat": "Miami Heat",
	"Orlando Magic": "Orlando Magic",
	"Washington Wizards": "Washington Wizards",
	"Denver Nuggets": "Denver Nuggets",
	"Minnesota Timberwolves": "Minnesota Timberwolves",
	"Oklahoma City Thunder": "Oklahoma City Thunder",
	"Portland Trail Blazers": "Portland Trail Blazers",
	"Golden State Warriors": "Golden State Warriors",
	"Los Angeles Lakers": "Los Angeles Lakers",
	"Los Angeles Clippers": "LA Clippers",
	"Phoenix Suns": "Phoenix Suns",
	"Sacramento Kings": "Sacramento Kings",
	"Dallas Mavericks": "Dallas Mavericks",
	"Houston Rockets": "Houston Rockets",
	"Memphis Grizzlies": "Memphis Grizzlies",
	"New Orleans Pelicans": "New Orleans Pelicans",
	"San Antonio Spurs": "San Antonio Spurs"
};